# -*- coding: utf-8 -*-
"""Metodo_trapezio_134498.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11RO03UFvx1gRtLfYgt4G70v7sPRXeWR7

#Autor: Matheus Teixeira de Souza

#Resumo: O método do trapézio procura aproximar a área da curva de uma função pela área de um trapézio.

#A ideia principal do método, é aproximar por uma reta (um polinômio de primeiro grau) atravez da equação que representa o método do trapézio, definida como : ∫ a b f ( x ) d x ≈ f ( a ) + f ( b ) 2 ( b − a ).
"""

import numpy as np  # Importa a biblioteca NumPy para operações matemáticas

# Definição da função a ser integrada
def f(x):
    # Função fornecida no problema
    return 0.2 + 25*x - 200*x**2 + 675*x**3 - 900*x**4 + 400*x**5

# Parâmetros de integração
a = 0  # Início do intervalo de integração
b = 0.8  # Final do intervalo de integração
n = 2  # Número de subintervalos para a Regra do Trapézio

# Cálculo do tamanho de cada subintervalo
h = (b - a) / n  # Comprimento de cada subintervalo

# Soma inicial com valores nos pontos extremos a e b
soma = f(a) + f(b)  # Soma dos valores da função nos pontos a e b

# Soma dos valores da função nos pontos intermediários
for i in range(1, n):
    xi = a + i * h  # Calcula o ponto xi
    soma += 2 * f(xi)  # Adiciona duas vezes o valor da função em xi à soma

# Cálculo da integral aproximada usando a fórmula da Regra do Trapézio
I_aproximado = (h / 2) * soma  # Integral aproximada

# Valor exato da integral fornecido no problema
I_exato = 1.640533  # Valor exato da integral

# Cálculo do erro absoluto verdadeiro
erro_absoluto_verdadeiro = abs(I_exato - I_aproximado)  # Diferença entre o valor exato e o aproximado

# Cálculo do erro aproximado E1
# A função f_prime é a derivada de primeira ordem da função fornecida
f_prime = lambda x: 25 - 400*x + 2025*x**2 - 3600*x**3 + 2000*x**4
# Calcula o erro aproximado usando a segunda derivada da função no ponto b
erro_aproximado_E1 = (-((b-a) * h**2) / 12) * f_prime(b)

# Resultados impressos na tela
print(f"Integral aproximada: {I_aproximado:.6f}")  # Mostra a integral aproximada
print(f"Erro absoluto verdadeiro: {erro_absoluto_verdadeiro:.6f}")  # Mostra o erro absoluto verdadeiro
print(f"Erro aproximado E1: {erro_aproximado_E1:.6f}")  # Mostra o erro aproximado E1